# default hana kpis with styles and sources

kpis = [
    ('1' ,'' ,'' ,'0' ,'Host' ,'' ,'' ,'' ,'0' ,'0'),
    ('1.01' ,'M_LOAD_HISTORY_HOST' ,'CPU' ,'1' ,'CPU' ,'CPU Used by all processes' ,'%' ,'%' ,'16711680' ,'2'),
    ('1.02' ,'M_LOAD_HISTORY_HOST' ,'MEMORY_RESIDENT' ,'10' ,'Database Resident Memory' ,'Physical memory used for all HANA processes' ,'Byte' ,'MB' ,'65280' ,'3'),
    ('1.03' ,'M_LOAD_HISTORY_HOST' ,'MEMORY_TOTAL_RESIDENT' ,'10' ,'Total Resident Memory' ,'Physical memory used for all processes' ,'Byte' ,'MB' ,'25600' ,'3'),
    ('1.04' ,'M_LOAD_HISTORY_HOST' ,'MEMORY_SIZE' ,'10' ,'Physical Memory Size' ,'Physical memory size' ,'Byte' ,'MB' ,'25600' ,'2'),
    ('1.05' ,'M_LOAD_HISTORY_HOST' ,'MEMORY_USED' ,'10' ,'Database Used Memory' ,'Memory used for all HANA processes' ,'Byte' ,'MB' ,'65280' ,'2'),
    ('1.06' ,'M_LOAD_HISTORY_HOST' ,'MEMORY_ALLOCATION_LIMIT' ,'10' ,'Database Allocation Limit' ,'Memory allocation limit for all processes of HANA instance' ,'Byte' ,'MB' ,'25600' ,'2'),
    ('1.07' ,'M_LOAD_HISTORY_HOST' ,'DISK_USED' ,'11' ,'Disk Used' ,'Disk used' ,'Byte' ,'GB' ,'255' ,'2'),
    ('1.08' ,'M_LOAD_HISTORY_HOST' ,'DISK_SIZE' ,'11' ,'Disk Size' ,'Disk size' ,'Byte' ,'GB' ,'139' ,'2'),
    ('1.09' ,'M_LOAD_HISTORY_HOST' ,'NETWORK_IN' ,'12' ,'Network In' ,'Bytes read from network by all processes' ,'Byte/sample' ,'MB/sec' ,'65535' ,'2'),
    ('1.10' ,'M_LOAD_HISTORY_HOST' ,'NETWORK_OUT' ,'12' ,'Network Out' ,'Bytes written to network by all processes' ,'Byte/sample' ,'MB/sec' ,'16711935' ,'2'),
    ('1.11' ,'M_LOAD_HISTORY_HOST' ,'SWAP_IN' ,'13' ,'Swap In' ,'Bytes read from swap by all processes (pswpin line in /proc/vmstat * sysconf(_SC_PAGESIZE))' ,'Byte/sample' ,'MB/sec' ,'65535' ,'3'),
    ('1.12' ,'M_LOAD_HISTORY_HOST' ,'SWAP_OUT' ,'13' ,'Swap Out' ,'Bytes written To swap by all processes (pswpout line in /proc/vmstat * sysconf(_SC_PAGESIZE))' ,'Byte/sample' ,'MB/sec' ,'16711935' ,'3'),
    ('2' ,'' ,'' ,'0' ,'Service' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.01' ,'M_LOAD_HISTORY_SERVICE' ,'CPU' ,'1' ,'CPU' ,'CPU used by Service' ,'%' ,'%' ,'16711680' ,'1'),
    ('2.02' ,'M_LOAD_HISTORY_SERVICE' ,'SYSTEM_CPU' ,'1' ,'System CPU' ,'OS Kernel/System CPU used by Service' ,'%' ,'%' ,'9109504' ,'1'),
    ('2.02' ,'M_LOAD_HISTORY_SERVICE' ,'MEMORY_USED' ,'10' ,'Memory Used' ,'Memory used by Service' ,'Byte' ,'MB' ,'65280' ,'1'),
    ('2.03' ,'M_LOAD_HISTORY_SERVICE' ,'MEMORY_ALLOCATION_LIMIT' ,'10' ,'Memory Allocation Limit' ,'Memory allocation limit for Service' ,'Byte' ,'MB' ,'25600' ,'3'),
    ('2.04' ,'M_LOAD_HISTORY_SERVICE' ,'HANDLE_COUNT' ,'0' ,'Handles' ,'Number of open handles' ,'' ,'' ,'8388736' ,'1'),
    ('2.05' ,'M_LOAD_HISTORY_SERVICE' ,'PING_TIME' ,'0' ,'Ping Time' ,'Duration of Service ping request (THREAD_METHOD=''__nsWatchdog''). This request includes the collection of service specific KPI''s' ,'msec' ,'msec' ,'10824234' ,'1'),
    ('2.06' ,'M_LOAD_HISTORY_SERVICE' ,'SWAP_IN' ,'13' ,'Swap In' ,'Bytes read from swap by Service (column 12(majflt) in /proc/<pid>/stat * sysconf(_SC_PAGESIZE))' ,'Byte/sample' ,'MB/sec' ,'65535' ,'1'),
    ('2.10' ,'' ,'' ,'0' ,'SQL' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.10.01' ,'M_LOAD_HISTORY_SERVICE' ,'CONNECTION_COUNT' ,'0' ,'Open Connections' ,'Number of open SQL connections' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.02' ,'M_LOAD_HISTORY_SERVICE' ,'INTERNAL_CONNECTION_COUNT' ,'0' ,'Internal Connections' ,'Number of open SQL internal connections' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.03' ,'M_LOAD_HISTORY_SERVICE' ,'EXTERNAL_CONNECTION_COUNT' ,'0' ,'External Connections' ,'Number of open SQL external connections' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.04' ,'M_LOAD_HISTORY_SERVICE' ,'IDLE_CONNECTION_COUNT' ,'0' ,'Idle Connections' ,'Number of open SQL idle connections' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.05' ,'M_LOAD_HISTORY_SERVICE' ,'TRANSACTION_COUNT' ,'0' ,'Open Transactions' ,'Number of open SQL transactions' ,'' ,'' ,'6316128' ,'1'),
    ('2.10.06' ,'M_LOAD_HISTORY_SERVICE' ,'INTERNAL_TRANSACTION_COUNT' ,'0' ,'Internal Transactions' ,'Number of internal transactions' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.07' ,'M_LOAD_HISTORY_SERVICE' ,'EXTERNAL_TRANSACTION_COUNT' ,'0' ,'External Transactions' ,'Number of external transactions' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.08' ,'M_LOAD_HISTORY_SERVICE' ,'USER_TRANSACTION_COUNT' ,'0' ,'User Transactions' ,'Number of user transactions' ,'' ,'' ,'4251856' ,'1'),
    ('2.10.09' ,'M_LOAD_HISTORY_SERVICE' ,'BLOCKED_TRANSACTION_COUNT' ,'0' ,'Blocked Transactions' ,'Number of blocked SQL transactions' ,'' ,'' ,'4210752' ,'1'),
    ('2.10.10' ,'M_LOAD_HISTORY_SERVICE' ,'STATEMENT_COUNT' ,'0' ,'Statements' ,'Number of finished SQL statements' ,'stmt/sample' ,'stmt/sec' ,'16753920' ,'1'),
    ('2.10.11' ,'M_LOAD_HISTORY_SERVICE' ,'COMMIT_ID_RANGE' ,'14' ,'Active Commit ID Range' ,'Range between newest and oldest active Commit ID' ,'' ,'' ,'11393254' ,'1'),
    ('2.10.12' ,'M_LOAD_HISTORY_SERVICE' ,'MVCC_VERSION_COUNT' ,'14' ,'Active Versions' ,'Number of active MVCC versions' ,'' ,'' ,'11393254' ,'3'),
    ('2.10.13' ,'M_LOAD_HISTORY_SERVICE' ,'PENDING_SESSION_COUNT' ,'14' ,'Pending Session Request Count' ,'Number of pending requests' ,'' ,'' ,'65535' ,'1'),
    ('2.11' ,'' ,'' ,'0' ,'Row Store' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.11.1' ,'M_LOAD_HISTORY_SERVICE' ,'RECORD_LOCK_COUNT' ,'14' ,'Acquired Record Locks' ,'Number of acquired record locks' ,'' ,'' ,'65280' ,'3'),
    ('2.12' ,'' ,'' ,'0' ,'Column Store' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.12.2' ,'M_LOAD_HISTORY_SERVICE' ,'CS_READ_COUNT' ,'0' ,'Read Requests' ,'Number of read requests (select)' ,'req/sample' ,'req/sec' ,'16753920' ,'1'),
    ('2.12.3' ,'M_LOAD_HISTORY_SERVICE' ,'CS_WRITE_COUNT' ,'0' ,'Write Requests' ,'Number of write requests (insert,update,delete)' ,'req/sample' ,'req/sec' ,'10824234' ,'1'),
    ('2.12.4' ,'M_LOAD_HISTORY_SERVICE' ,'CS_MERGE_COUNT' ,'0' ,'Merge Requests' ,'Number of merge requests' ,'req/sample' ,'req/sec' ,'8388736' ,'1'),
    ('2.12.5' ,'M_LOAD_HISTORY_SERVICE' ,'CS_UNLOAD_COUNT' ,'0' ,'Column Unloads' ,'Number of column unloads' ,'req/sample' ,'req/sec' ,'15631086' ,'1'),
    ('2.13' ,'' ,'' ,'0' ,'Threads' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.13.1' ,'M_LOAD_HISTORY_SERVICE' ,'ACTIVE_THREAD_COUNT' ,'0' ,'Active Threads' ,'Number of active threads' ,'' ,'' ,'255' ,'1'),
    ('2.13.2' ,'M_LOAD_HISTORY_SERVICE' ,'WAITING_THREAD_COUNT' ,'0' ,'Waiting Threads' ,'Number of waiting threads' ,'' ,'' ,'65280' ,'1'),
    ('2.13.3' ,'M_LOAD_HISTORY_SERVICE' ,'TOTAL_THREAD_COUNT' ,'0' ,'Total Threads' ,'Total number of threads' ,'' ,'' ,'15631086' ,'1'),
    ('2.13.4' ,'M_LOAD_HISTORY_SERVICE' ,'ACTIVE_SQL_EXECUTOR_COUNT' ,'0' ,'Active SqlExecutors' ,'Number of active SqlExecutors' ,'' ,'' ,'16711680' ,'1'),
    ('2.13.6' ,'M_LOAD_HISTORY_SERVICE' ,'WAITING_SQL_EXECUTOR_COUNT' ,'0' ,'Waiting SqlExecutors' ,'Number of waiting SqlExecutors' ,'' ,'' ,'16711935' ,'1'),
    ('2.13.7' ,'M_LOAD_HISTORY_SERVICE' ,'TOTAL_SQL_EXECUTOR_COUNT' ,'0' ,'Total SqlExecutors' ,'Total number of SqlExecutors' ,'' ,'' ,'16753920' ,'1'),
    ('2.20' ,'' ,'' ,'0' ,'Persistence' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.20.1' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_WRITE_SIZE' ,'15' ,'Data Write Size' ,'Bytes written to data area' ,'Byte/sample' ,'MB/sec' ,'16711680' ,'2'),
    ('2.20.2' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_WRITE_TIME' ,'16' ,'Data Write Time' ,'Time used for writing to data area' ,'usec/sample' ,'sec/sec' ,'16711680' ,'3'),
    ('2.20.3' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_WRITE_SIZE' ,'15' ,'Log Write Size' ,'Bytes written to log area' ,'Byte/sample' ,'MB/sec' ,'16753920' ,'2'),
    ('2.20.4' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_WRITE_TIME' ,'16' ,'Log Write Time' ,'Time used for writing to log area' ,'usec/sample' ,'sec/sec' ,'16753920' ,'3'),
    ('2.20.5' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_READ_SIZE' ,'15' ,'Data Read Size' ,'Bytes read from data area' ,'Byte/sample' ,'MB/sec' ,'65280' ,'2'),
    ('2.20.6' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_READ_TIME' ,'16' ,'Data Read Time' ,'Time used for reading from data area' ,'usec/sample' ,'sec/sec' ,'65280' ,'3'),
    ('2.20.7' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_READ_SIZE' ,'15' ,'Log Read Size' ,'Bytes read from log area' ,'Byte/sample' ,'MB/sec' ,'25600' ,'2'),
    ('2.20.8' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_READ_TIME' ,'16' ,'Log Read Time' ,'Time used for reading from log area' ,'usec/sample' ,'sec/sec' ,'25600' ,'3'),
    ('2.21' ,'' ,'' ,'0' ,'Backup' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.21.1' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_BACKUP_WRITE_SIZE' ,'15' ,'Data Backup Write Size' ,'Bytes written to data backup' ,'Byte/sample' ,'MB/sec' ,'255' ,'2'),
    ('2.21.2' ,'M_LOAD_HISTORY_SERVICE' ,'DATA_BACKUP_WRITE_TIME' ,'16' ,'Data Backup Write Time' ,'Time used for writing to data backup' ,'usec/sample' ,'sec/sec' ,'255' ,'3'),
    ('2.21.3' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_BACKUP_WRITE_SIZE' ,'15' ,'Log Backup Write Size' ,'Bytes written to log backup' ,'Byte/sample' ,'MB/sec' ,'11393254' ,'2'),
    ('2.21.4' ,'M_LOAD_HISTORY_SERVICE' ,'LOG_BACKUP_WRITE_TIME' ,'16' ,'Log Backup Write Time' ,'Time used for writing to log backup' ,'usec/sample' ,'sec/sec' ,'11393254' ,'3'),
    ('2.30' ,'' ,'' ,'0' ,'Synchronization Primitives' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.30.1' ,'M_LOAD_HISTORY_SERVICE' ,'MUTEX_COLLISION_COUNT' ,'0' ,'Mutex Collisions' ,'Number of collisions on mutexes' ,'col/sample' ,'col/sec' ,'16753920' ,'2'),
    ('2.30.2' ,'M_LOAD_HISTORY_SERVICE' ,'READ_WRITE_LOCK_COLLISION_COUNT' ,'0' ,'Read/Write Lock Collisions' ,'Number of collisions on read/write locks' ,'col/sample' ,'col/sec' ,'10824234' ,'2'),
    ('2.40' ,'' ,'' ,'0' ,'Session Admission Control' ,'' ,'' ,'' ,'0' ,'0'),
    ('2.40.1' ,'M_LOAD_HISTORY_SERVICE' ,'ADMISSION_CONTROL_ADMIT_COUNT' ,'17' ,'Admission Control Admitted Reque' ,'Number of session requests admitted by admission control' ,'req/sample' ,'req/sec' ,'255' ,'1'),
    ('2.40.2' ,'M_LOAD_HISTORY_SERVICE' ,'ADMISSION_CONTROL_REJECT_COUNT' ,'17' ,'Admission Control Rejected Reque' ,'Number of session requests rejected by admission control' ,'req/sample' ,'req/sec' ,'255' ,'1'),
    ('2.40.3' ,'M_LOAD_HISTORY_SERVICE' ,'ADMISSION_CONTROL_QUEUE_SIZE' ,'17' ,'Admission Control Waiting Reques' ,'Number of session requests waiting in admission control queue' ,'req/sample' ,'req/sec' ,'255' ,'1'),
    ('2.40.4' ,'M_LOAD_HISTORY_SERVICE' ,'ADMISSION_CONTROL_WAIT_TIME' ,'0' ,'Admission Control Wait Time' ,'Total wait time of session requests queued in admission control queue' ,'usec/sample' ,'sec/sec' ,'255' ,'1')
]

# m_load_history to nameserver.trc mapping
mapKPIs = [
    ('cpuUsed'           , 'host', 'CPU'),
    ('memoryResident'    , 'host', 'MEMORY_RESIDENT'),
    ('memoryTotalResident', 'host', 'MEMORY_TOTAL_RESIDENT'),
    ('memorySize'        , 'host', 'MEMORY_SIZE'),
    ('memoryUsed'        , 'host', 'MEMORY_USED'),
    ('memoryLimit'       , 'host', 'MEMORY_ALLOCATION_LIMIT'),
    ('diskUsed'          , 'host', 'DISK_USED'),
    ('diskSize'          , 'host', 'DISK_SIZE'),
    ('networkIn'         , 'host', 'NETWORK_IN'),
    ('networkOut'        , 'host', 'NETWORK_OUT'),
    ('swapIn'            , 'host', 'SWAP_IN'),
    ('swapOut'           , 'host', 'SWAP_OUT'),
    ('indexserverCpu'    , 'service', 'CPU'),
    ('indexserverCpuSys' , 'service', 'SYSTEM_CPU'),
    ('indexserverMemUsed', 'service', 'MEMORY_USED'),
    ('indexserverMemLimit', 'service', 'MEMORY_ALLOCATION_LIMIT'),
    ('indexserverHandles', 'service', 'HANDLE_COUNT'),
    ('indexserverPingtime'                  , 'service', 'PING_TIME'),
    ('indexserverPingtime'                  , 'service', 'SWAP_IN'),
    ('sqlConnections'                  , 'service', 'CONNECTION_COUNT'),
    ('internalConnections'                  , 'service', 'INTERNAL_CONNECTION_COUNT'),
    ('externalConnections'                  , 'service', 'EXTERNAL_CONNECTION_COUNT'),
    ('idleConnections'                  , 'service', 'IDLE_CONNECTION_COUNT'),
    ('sqlTransactions'                  , 'service', 'TRANSACTION_COUNT'),
    ('internalTransactions'                  , 'service', 'INTERNAL_TRANSACTION_COUNT'),
    ('externalTransactions'                  , 'service', 'EXTERNAL_TRANSACTION_COUNT'),
    ('userTransactions'                  , 'service', 'USER_TRANSACTION_COUNT'),
    ('sqlBlockedTrans'                  , 'service', 'BLOCKED_TRANSACTION_COUNT'),
    ('sqlStatements'                  , 'service', 'STATEMENT_COUNT'),
    ('cidRange'                  , 'service', 'COMMIT_ID_RANGE'),
    ('mvccNum'                  , 'service', 'MVCC_VERSION_COUNT'),
    ('pendingRequestCount'                  , 'service', 'PENDING_SESSION_COUNT'),
    ('acquiredRecordLocks'                  , 'service', 'RECORD_LOCK_COUNT'),
    ('searchCount'                  , 'service', 'CS_READ_COUNT'),
    ('indexingCount'                  , 'service', 'CS_WRITE_COUNT'),
    ('mergeCount'                  , 'service', 'CS_MERGE_COUNT'),
    ('unloadCount'                  , 'service', 'CS_UNLOAD_COUNT'),
    ('indexserverThreads'                  , 'service', 'ACTIVE_THREAD_COUNT'),
    ('waitingThreads'                  , 'service', 'WAITING_THREAD_COUNT'),
    ('totalThreads'                  , 'service', 'TOTAL_THREAD_COUNT'),
    ('activeSqlExecutors'                  , 'service', 'ACTIVE_SQL_EXECUTOR_COUNT'),
    ('waitingSqlExecutors'                  , 'service', 'WAITING_SQL_EXECUTOR_COUNT'),
    ('totalSqlExecutors'                  , 'service', 'TOTAL_SQL_EXECUTOR_COUNT'),
    ('dataWriteSize'                  , 'service', 'DATA_WRITE_SIZE'),
    ('dataWriteTime'                  , 'service', 'DATA_WRITE_TIME'),
    ('logWriteSize'                  , 'service', 'LOG_WRITE_SIZE'),
    ('logWriteTime'                  , 'service', 'LOG_WRITE_TIME'),
    ('dataReadSize'                  , 'service', 'DATA_READ_SIZE'),
    ('dataReadTime'                  , 'service', 'DATA_READ_TIME'),
    ('logReadSize'                  , 'service', 'LOG_READ_SIZE'),
    ('logReadTime'                  , 'service', 'LOG_READ_TIME'),
    ('dataBackupWriteSize'                  , 'service', 'DATA_BACKUP_WRITE_SIZE'),
    ('dataBackupWriteTime'                  , 'service', 'DATA_BACKUP_WRITE_TIME'),
    ('logBackupWriteSize'                  , 'service', 'LOG_BACKUP_WRITE_SIZE'),
    ('logBackupWriteTime'                  , 'service', 'LOG_BACKUP_WRITE_TIME'),
    ('mutexCollisionCount'                  , 'service', 'MUTEX_COLLISION_COUNT'),
    ('readWriteLockCollisionCount'                  , 'service', 'READ_WRITE_LOCK_COLLISION_COUNT'),
    ('admissinControlAdmitCount'                  , 'service', 'ADMISSION_CONTROL_ADMIT_COUNT'),
    ('admissionControlRejectCount'                  , 'service', 'ADMISSION_CONTROL_REJECT_COUNT'),
    ('admissionControlWaitingRequests'                  , 'service', 'ADMISSION_CONTROL_QUEUE_SIZE'),
    ('admissionControlWaitTime'                  , 'service', 'ADMISSION_CONTROL_WAIT_TIME')    
]

def findKPI(hierarchy):
    for r in kpis:
        if r[0] == hierarchy:
            return {
                'hierarchy':    r[0],
                'type':         r[1],
                'name':         r[2],
                'group':        r[3],
                'sUnit':        r[4],
                'dUnit':        r[5],
                'label':        r[6],
                'description':  r[7],
                'color':        r[8],
                'style':        r[9],
            }
    return None